name: Deploy DotNet project to Azure Function App

on:
  push

# CONFIGURATION
# 1. Set up the following secrets in your repository:
#   - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#   - POSTGRES_HOST
#   - POSTGRES_DB
#   - POSTGRES_USER
#   - POSTGRES_PASSWORD
#
# 2. Ajuste os valores conforme necessário
env:
  AZURE_FUNCTIONAPP_NAME: 'fastfood-auth-function'   # nome da Function App no Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Soat.Eleven.FastFood.AuthFunc'  # caminho para o projeto
  DOTNET_VERSION: '8.0.x'  # versão do dotnet

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          popd

      - name: Build project
        shell: pwsh
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Set Database Connection String'
        shell: pwsh
        run: |
          $connectionString = "Host=${{ secrets.POSTGRES_HOST }};Port=5432;Database=${{ secrets.POSTGRES_DB }};Username=${{ secrets.POSTGRES_USER }};Password=${{ secrets.POSTGRES_PASSWORD }};SslMode=Require;TrustServerCertificate=true"
          echo "AZURE_SQL_CONNECTIONSTRING=$connectionString" >> $env:GITHUB_ENV

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        env:
          AZURE_SQL_CONNECTIONSTRING: ${{ env.AZURE_SQL_CONNECTIONSTRING }}
